executable              = data_prep.sh
arguments               = $(ClusterId) $(ProcId)
output                  = data_prep.$(ClusterId).$(ProcId).out
error                   = data_prep.$(ClusterId).$(ProcId).err
log                     = data_prep.$(ClusterId).log
transfer_input_files    = data_prep.py 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_CPUs = 20
+JobFlavour = "nextweek"  
queue 3
