executable              = run_dataset4.sh
arguments               = $(ClusterId) $(ProcId)
output                  = training_4_.$(ClusterId).$(ProcId).out
error                   = training_4_.$(ClusterId).$(ProcId).err
log                     = training_4_.$(ClusterId).log
transfer_input_files    = training,models,loss_info
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_MEMORY = 40G
+JobFlavour = "testmatch"  
queue 13 
