executable              = run_retrain3.sh
arguments               = $(ClusterId) $(ProcId)
output                  = retraining_3_.$(ClusterId).$(ProcId).out
error                   = retraining_3_.$(ClusterId).$(ProcId).err
log                     = retraining_3_.$(ClusterId).log
transfer_input_files    = training,models,loss_info,checkpoints
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_MEMORY = 40G
+JobFlavour = "nextweek"  
queue 4 
