executable              = run_single.sh
arguments               = $(ClusterId) $(ProcId)
output                  = training.$(ClusterId).$(ProcId).out
error                   = training.$(ClusterId).$(ProcId).err
log                     = training.$(ClusterId).log
transfer_input_files    = training,models,loss_info
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_MEMORY = 40G  
queue
